name: Exercice 4 - Inspection Michelin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération de la carte (Checkout)
      uses: actions/checkout@v4

    - name: Préparation de la cuisine (Setup Node)
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Installation des ustensiles (Install)
      run: npm ci

    # ÉTAPE CRITIQUE : Vérification de la présentation
    - name: Vérification de la carte (Lint)
      run: npm run lint

    # Cette étape ne se lance QUE si le Lint a réussi
    - name: Dégustation (Tests)
      run: npm run test