name: Exercice 4 et 5 - Inspection & Franchises

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  inspection-et-test:
    runs-on: ubuntu-latest

    # AJOUT : La matrice pour créer 3 jobs parallèles
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Récupération de la carte (Checkout)
      uses: actions/checkout@v4

    # MODIFICATION : On utilise la variable de la matrice ici
    - name: Préparation de la cuisine (Setup Node ${{ matrix.node-version }})
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Installation des ustensiles (Install)
      run: npm ci

    # Le Lint se lance sur chaque version (pour être sûr que le code est propre partout)
    - name: Vérification de la carte (Lint)
      run: npm run lint

    # Si le Lint passe, on lance les tests
    - name: Dégustation (Tests)
      run: npm run test